spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/sb_demo
    username: postgres
    password: root
  jpa:
    show-sql: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8181/realms/demoProject
          jwk-set-uri: ${spring.security.oauth2.resourceserver.jwt.issuer-uri}/protocol/openid-connect/certs


server:
  port: 8080


keycloak:
  auth-server-url: http://localhost:8181/auth
  realm: demoProject
  resource: demo-pro-rest-api
  credentials:
    secret: